Vedic-Technologies/manipal-client

src/components/ui/Leftbar.js
=> left icon changes

src/pages/monthly_income/expense.tsx, src/pages/monthly_income/income.tsx
=> changed chart type in income/exp page

src/components/ConfirmationModal.tsx, src/pages/patient/Patient.tsx
=> added delete confirmation dialogue model

src/index.css, src/pages/patient/Patient.tsx
=> not so red anymore&& added patient satatus

src/pages/patient/Patient.tsx, src/pages/prescription/PresCription.tsx
=> 1. now actual image will show up in patient list, 2. image can be attached at registration of new patients

src/pages/payment/PaymentEntry.tsx, src/pages/prescription/PresCription.tsx
Reverts Vedic-Technologies/manipal-client#40
=> Revert "Harsh"

src/custom_components/ui/Leftbar.js, src/custom_components/ui/leftbar.css, src/index.css, src/pages/patient/AllPatients.tsx, src/pages/payments_details/PatientPaymentsDetails.tsx
=> edit <-> copy, 2.search func in all patients, not yet in payment details

src/custom_components/ConfirmationModal.tsx, src/custom_components/JobDoneAlert.tsx, src/pages/patient/AllPatients.tsx, src/pages/payments_details/PatientPaymentsDetails.tsx
=> added custom alerts instead of window alerts / fixed PatientDetailCard fields

src/custom_components/ui/Leftbar.js, src/custom_components/ui/leftbar.css
*leftbar doesnot strech on opening patient/payment anymore
*active stays where it was before refreshing..
=> fixed leftbar.

src/pages/payment/DailyPayment.tsx
after submit  show ( ✔ ) right shine
=>  button click krne pe (submit krne me )sucess  wala kam done

src/API/API.tsx, src/components/ui/button.tsx, src/pages/prescription/PeriarthritisShoulderForm.tsx
=> button size fixed in Doctor prescription/submission is not done yet.

src/pages/prescription/DoctorPrescription.tsx, src/pages/prescription/PeriarthritisShoulderForm.tsx
=> error in posting Prescription details

src/API/API.tsx, src/pages/prescription/PeriarthritisShoulderForm.tsx
=> successfully posting shoulderPrescription

src/pages/monthly_income/MonthlyIncExp.tsx, src/pages/payments_details/PatientPaymentsDetails.tsx
show income according to date choose date  and see the income .
=> monthly income task done

src/API/API.tsx, src/pages/landing/LandingPage.tsx, src/pages/landing/cards/DailyIncomeCard.js, src/pages/landing/cards/MaleFemaleRatio.tsx, src/pages/landing/cards/TotalPatient.tsx, src/pages/landing/cards/TotalRevenue.tsx, src/pages/landing/infocard/InfoCard.tsx, src/pages/landing/infocard/infoData.tsx, src/pages/monthly_income/MonthlyIncExp.tsx
=> dynamic dashboard

src/API/API.tsx, src/custom_components/StartupApiCall.tsx, src/pages/login/LoginBlockNew.tsx
cookies saved and all patients  filter by admin specific
=> login with credentials

src/API/API.tsx, src/pages/login/LoginBlockNew.tsx
header based authentication and login is mandatory
=> header based authentication

src/custom_components/StartupApiCall.tsx
header include in startUpApiCall
=> startup data

src/pages/payment/DailyPayment.tsx, src/pages/payment/Opd.tsx
=> daily payment

src/API/API.tsx, src/pages/login/LoginBlockNew.tsx, src/pages/staff/StaffSignup.js
fix lgin by admin and staff , changes in staff page , change in RTK for getting all staff data
=> login staff and RTK changes

src/pages/prescription/PatientFormStaff.tsx
Patient register by staff should be empty after registration.
done this task
=> after submit clear all filed

src/pages/patient/PatientPaymentCard.tsx, src/pages/payment/DailyPayment.tsx, src/pages/payment/DiscountPayment.tsx, src/pages/payment/Opd.tsx, src/pages/payment/PaymentCard.js, src/pages/payment/PaymentDetails.tsx
=> made payment card responsive/ can only make payment once a day

src/pages/patient/PatientPaymentCard.tsx, src/pages/payment/PaymentEntry.tsx
Payment entry ka pahla card responsive bnayiye.
this task is complete.
=> payment card responsive

src/pages/patient/PatientDetails.tsx
all patient show click on view detail
=> all patient show click on view detail

src/pages/prescription/PatientFormStaff.tsx
improved logic for default user image
=> default image removed

src/pages/patient/PatientDetailCard.tsx
shrink default image of patient in detail page
=> default image shrink

src/API/API.tsx, src/pages/patient/PatientDetailCard.tsx
fix image not posting on server
fix capture button position
=> image not posting

src/pages/payments_details/PatientPaymentsDetails.tsx
=> more filters in payment details

src/pages/payments_details/PatientPaymentsDetails.tsx
=> bug fixed and added some logics

src/pages/patient/AllPatients.tsx, src/pages/payment/DiscountPayment.tsx, src/pages/payments_details/PatientPaymentsDetails.tsx, src/pages/prescription/PatientFormStaff.tsx
- fade out feedback when deleting payment
- patient deleting feedback emplemented
- removed delay in closing after confirmation in deleting amount and patient
- fixed type of contact and invalid entry in age , height, weight
- fixed error in discount while selecting range
=> alert updates and bug fixes

src/custom_components/jobDoneVarient.tsx, src/pages/patient/AllPatients.tsx, src/pages/payment/DiscountPayment.tsx, src/pages/payments_details/PatientPaymentsDetails.tsx, src/pages/prescription/PatientFormStaff.tsx, src/pages/staff/StaffSignup.js
=> update alerts in all pages
